import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alpageush
 */
public class okno extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    String path = "C:\\Users\\Alpageush\\Documents\\NetBeansProjects\\rychu_peja_jest_przezabawny\\src\\main\\java\\rsc\\";
    public okno() {
        initComponents();
        logo.setIcon(new ImageIcon(path + "logo.png"));
        color_changer(Color.red);
        setLocationRelativeTo(null);
        okno_info.setBackground(Color.red);
        okno_help.setBackground(Color.red);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okno_info = new javax.swing.JFrame();
        tekst_info = new javax.swing.JLabel();
        okno_help = new javax.swing.JFrame();
        tekst_help = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pole_tekstowe = new javax.swing.JTextArea();
        przycisk_zapisz = new javax.swing.JButton();
        przycisk_otworz = new javax.swing.JButton();
        przycisk_zamknij = new javax.swing.JButton();
        menu_pasek = new javax.swing.JMenuBar();
        menu_plik = new javax.swing.JMenu();
        menu_zapisz = new javax.swing.JMenuItem();
        menu_wczytaj = new javax.swing.JMenuItem();
        menu_zamknij = new javax.swing.JMenuItem();
        menu_edycja = new javax.swing.JMenu();
        menu_edycja_czcionka = new javax.swing.JMenu();
        czcionka_tahoma = new javax.swing.JMenuItem();
        czcionka_times = new javax.swing.JMenuItem();
        czcionka_arial = new javax.swing.JMenuItem();
        czcionka_comic = new javax.swing.JMenuItem();
        menu_edycja_kolor = new javax.swing.JMenu();
        kolor_czerwony = new javax.swing.JMenuItem();
        kolor_zielony = new javax.swing.JMenuItem();
        kolor_niebieski = new javax.swing.JMenuItem();
        kolor_rozowy = new javax.swing.JMenuItem();
        kolor_magenta = new javax.swing.JMenuItem();
        kolor_czarny = new javax.swing.JMenuItem();
        menu_info = new javax.swing.JMenu();
        menu_oprogramie = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenuItem();

        okno_info.setTitle("Informacje");
        okno_info.setMinimumSize(new java.awt.Dimension(371, 378));
        okno_info.setResizable(false);
        okno_info.setType(java.awt.Window.Type.UTILITY);

        tekst_info.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tekst_info.setText("<html>\n<center>\n<h1>O PROGRAMIE</h1>\n<b>Autor:</b> Alan Łuszczak<br>\n<b>Język:</b> Java<br>\n<b>Data kompilacji:</b> 30/01/2021<br>\n</center>\n</html>");

        javax.swing.GroupLayout okno_infoLayout = new javax.swing.GroupLayout(okno_info.getContentPane());
        okno_info.getContentPane().setLayout(okno_infoLayout);
        okno_infoLayout.setHorizontalGroup(
            okno_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okno_infoLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(tekst_info, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        okno_infoLayout.setVerticalGroup(
            okno_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okno_infoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(tekst_info, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        okno_help.setTitle("Informacje");
        okno_help.setMinimumSize(new java.awt.Dimension(371, 378));
        okno_help.setResizable(false);
        okno_help.setType(java.awt.Window.Type.UTILITY);

        tekst_help.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tekst_help.setText("<html>\n<center>\n<h1>POMOC</h1>\nNiniejszy program służy do pisania.<br>\nJak nie działa to nie działa<br>\ni koniec\n</center>\n</html>");
        tekst_help.setToolTipText("");

        javax.swing.GroupLayout okno_helpLayout = new javax.swing.GroupLayout(okno_help.getContentPane());
        okno_help.getContentPane().setLayout(okno_helpLayout);
        okno_helpLayout.setHorizontalGroup(
            okno_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okno_helpLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(tekst_help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        okno_helpLayout.setVerticalGroup(
            okno_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okno_helpLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(tekst_help, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Alan Luszczak");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(666, 420));
        setMinimumSize(new java.awt.Dimension(666, 420));
        setResizable(false);

        logo.setMaximumSize(new java.awt.Dimension(91, 91));
        logo.setMinimumSize(new java.awt.Dimension(91, 91));
        logo.setPreferredSize(new java.awt.Dimension(91, 91));

        pole_tekstowe.setColumns(20);
        pole_tekstowe.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        pole_tekstowe.setRows(5);
        jScrollPane1.setViewportView(pole_tekstowe);

        przycisk_zapisz.setText("Zapisz");
        przycisk_zapisz.setFocusable(false);
        przycisk_zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_zapiszActionPerformed(evt);
            }
        });

        przycisk_otworz.setText("Otwórz");
        przycisk_otworz.setFocusable(false);
        przycisk_otworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_otworzActionPerformed(evt);
            }
        });

        przycisk_zamknij.setText("Zamknij");
        przycisk_zamknij.setFocusable(false);
        przycisk_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(przycisk_zapisz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(przycisk_zamknij, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(przycisk_otworz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(przycisk_zapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(przycisk_otworz, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(przycisk_zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(jScrollPane1)
        );

        menu_plik.setText("Plik");

        menu_zapisz.setText("Zapisz");
        menu_zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zapiszActionPerformed(evt);
            }
        });
        menu_plik.add(menu_zapisz);

        menu_wczytaj.setText("Wczytaj");
        menu_wczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_wczytajActionPerformed(evt);
            }
        });
        menu_plik.add(menu_wczytaj);

        menu_zamknij.setText("Zamknij program");
        menu_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zamknijActionPerformed(evt);
            }
        });
        menu_plik.add(menu_zamknij);

        menu_pasek.add(menu_plik);

        menu_edycja.setText("Edycja");

        menu_edycja_czcionka.setText("Zmień czcionkę");

        czcionka_tahoma.setText("Tahoma");
        czcionka_tahoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czcionka_tahomaActionPerformed(evt);
            }
        });
        menu_edycja_czcionka.add(czcionka_tahoma);

        czcionka_times.setText("Times New Roman");
        czcionka_times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czcionka_timesActionPerformed(evt);
            }
        });
        menu_edycja_czcionka.add(czcionka_times);

        czcionka_arial.setText("Arial");
        czcionka_arial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czcionka_arialActionPerformed(evt);
            }
        });
        menu_edycja_czcionka.add(czcionka_arial);

        czcionka_comic.setText("Comic Sans");
        czcionka_comic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czcionka_comicActionPerformed(evt);
            }
        });
        menu_edycja_czcionka.add(czcionka_comic);

        menu_edycja.add(menu_edycja_czcionka);

        menu_edycja_kolor.setText("Zmień tło");

        kolor_czerwony.setText("Czerwone");
        kolor_czerwony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolor_czerwonyActionPerformed(evt);
            }
        });
        menu_edycja_kolor.add(kolor_czerwony);

        kolor_zielony.setText("Zielone");
        kolor_zielony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolor_zielonyActionPerformed(evt);
            }
        });
        menu_edycja_kolor.add(kolor_zielony);

        kolor_niebieski.setText("Niebieskie");
        kolor_niebieski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolor_niebieskiActionPerformed(evt);
            }
        });
        menu_edycja_kolor.add(kolor_niebieski);

        kolor_rozowy.setText("Różowe");
        kolor_rozowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolor_rozowyActionPerformed(evt);
            }
        });
        menu_edycja_kolor.add(kolor_rozowy);

        kolor_magenta.setText("Magenta");
        kolor_magenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolor_magentaActionPerformed(evt);
            }
        });
        menu_edycja_kolor.add(kolor_magenta);

        kolor_czarny.setText("Czarny");
        kolor_czarny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolor_czarnyActionPerformed(evt);
            }
        });
        menu_edycja_kolor.add(kolor_czarny);

        menu_edycja.add(menu_edycja_kolor);

        menu_pasek.add(menu_edycja);

        menu_info.setText("O programie");

        menu_oprogramie.setText("O programie");
        menu_oprogramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_oprogramieActionPerformed(evt);
            }
        });
        menu_info.add(menu_oprogramie);

        menu_help.setText("Help");
        menu_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_helpActionPerformed(evt);
            }
        });
        menu_info.add(menu_help);

        menu_pasek.add(menu_info);

        setJMenuBar(menu_pasek);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_zamknijActionPerformed

    private void menu_oprogramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_oprogramieActionPerformed
        //JOptionPane.showMessageDialog(this,"help");
        okno_info.show();
        okno_info.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_oprogramieActionPerformed

    private void menu_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_helpActionPerformed
        okno_help.show();
        okno_help.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_helpActionPerformed

    private void przycisk_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_zamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_przycisk_zamknijActionPerformed

    private void przycisk_zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_zapiszActionPerformed
        save();
    }//GEN-LAST:event_przycisk_zapiszActionPerformed

    private void kolor_czerwonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolor_czerwonyActionPerformed
        color_changer(Color.red);
    }//GEN-LAST:event_kolor_czerwonyActionPerformed

    private void menu_zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zapiszActionPerformed
        save();
    }//GEN-LAST:event_menu_zapiszActionPerformed

    private void kolor_zielonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolor_zielonyActionPerformed
        color_changer(Color.green);
    }//GEN-LAST:event_kolor_zielonyActionPerformed

    private void kolor_niebieskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolor_niebieskiActionPerformed
        color_changer(Color.blue);
    }//GEN-LAST:event_kolor_niebieskiActionPerformed

    private void kolor_rozowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolor_rozowyActionPerformed
        color_changer(Color.pink);
    }//GEN-LAST:event_kolor_rozowyActionPerformed

    private void kolor_magentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolor_magentaActionPerformed
        color_changer(Color.magenta);
    }//GEN-LAST:event_kolor_magentaActionPerformed

    private void kolor_czarnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolor_czarnyActionPerformed
        color_changer(Color.black);
    }//GEN-LAST:event_kolor_czarnyActionPerformed

    private void czcionka_tahomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czcionka_tahomaActionPerformed
        font_changer("Tahoma");
    }//GEN-LAST:event_czcionka_tahomaActionPerformed

    private void czcionka_timesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czcionka_timesActionPerformed
        font_changer("Times New Roman");
    }//GEN-LAST:event_czcionka_timesActionPerformed

    private void czcionka_arialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czcionka_arialActionPerformed
        font_changer("Arial");
    }//GEN-LAST:event_czcionka_arialActionPerformed

    private void czcionka_comicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czcionka_comicActionPerformed
        font_changer("Comic Sans");
    }//GEN-LAST:event_czcionka_comicActionPerformed

    private void menu_wczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_wczytajActionPerformed
        open();
    }//GEN-LAST:event_menu_wczytajActionPerformed

    private void przycisk_otworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_otworzActionPerformed
        open();
    }//GEN-LAST:event_przycisk_otworzActionPerformed

    void open() {
        File plik = new File(path + "text.txt");
        if(!plik.exists()) return;
        Scanner sc = new Scanner(plik);
        //if(sc.ha)
        pole_tekstowe.setText(sc.toString());
    }
    
    void save() {
        File plik = new File(path + "text.txt");
        FileWriter fs = new FileWriter(plik);
        if(plik.exists()) {
            try {
                FileReader fr = new FileReader(plik);
                fs.write(pole_tekstowe.getText());
                //pole_tekstowe.setText(fr.read());
                fr.close();
                fs.close();
            } catch (IOException ex) {
                Logger.getLogger(okno.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                plik.createNewFile();
                fs.write(pole_tekstowe.getText());
            } catch (IOException ex) {
                Logger.getLogger(okno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    void color_changer(Color color) {
        przycisk_zapisz.setBackground(color);
        przycisk_zamknij.setBackground(color);
        przycisk_otworz.setBackground(color);
        panel.setBackground(color);
    }
    
    void font_changer(String font) {
        pole_tekstowe.setFont(new Font(font, Font.PLAIN, 13));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem czcionka_arial;
    private javax.swing.JMenuItem czcionka_comic;
    private javax.swing.JMenuItem czcionka_tahoma;
    private javax.swing.JMenuItem czcionka_times;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem kolor_czarny;
    private javax.swing.JMenuItem kolor_czerwony;
    private javax.swing.JMenuItem kolor_magenta;
    private javax.swing.JMenuItem kolor_niebieski;
    private javax.swing.JMenuItem kolor_rozowy;
    private javax.swing.JMenuItem kolor_zielony;
    private javax.swing.JLabel logo;
    private javax.swing.JMenu menu_edycja;
    private javax.swing.JMenu menu_edycja_czcionka;
    private javax.swing.JMenu menu_edycja_kolor;
    private javax.swing.JMenuItem menu_help;
    private javax.swing.JMenu menu_info;
    private javax.swing.JMenuItem menu_oprogramie;
    private javax.swing.JMenuBar menu_pasek;
    private javax.swing.JMenu menu_plik;
    private javax.swing.JMenuItem menu_wczytaj;
    private javax.swing.JMenuItem menu_zamknij;
    private javax.swing.JMenuItem menu_zapisz;
    private javax.swing.JFrame okno_help;
    private javax.swing.JFrame okno_info;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea pole_tekstowe;
    private javax.swing.JButton przycisk_otworz;
    private javax.swing.JButton przycisk_zamknij;
    private javax.swing.JButton przycisk_zapisz;
    private javax.swing.JLabel tekst_help;
    private javax.swing.JLabel tekst_info;
    // End of variables declaration//GEN-END:variables
}
